### ISSUE TITLE
Aktuální plán

### ISSUE THREAD

**Issue by JanTvrdik** [fitak/fitak#63]
Jak já vidím aktuální plán.
- [x] Opravy známé bugy #52 a #57
- [ ] Vyřešit „Tls na novem serveru“ https://github.com/fitak/fitak/issues/49
- [ ] Naprogramovat sledované tagy #54 #55 #56 #61
- [ ] Vyžadovat přihlášení už na homepage #62
- [ ] Vyřešit navigaci k odhlášení a uživatelským nastavení https://github.com/fitak/fitak/issues/64
- [ ] Naindexovat edux #23 
- [ ] Tagnout `v2.0.0-beta1` a spustit uzavřenou betu (na subdoméně). Udělal bych to obdobně jako u svojí bakalářky, tj. napsal bych do náhodně vybrané FB skupiny, že kdo má zájem se účastnit uzavřené bety ať mi pošle mail. Ideálně bych chtěl na testování 20 – 30 lidí.
- [ ] Vyhodnotit feedback, mimojiné v souvislosti s #60
- [ ] Tagnout `v2.0.0` a nasadit novou verzi na produkci
- [ ] Oznámit vydání nové verze spojené (?) s inzerátem na nábor nových lidí #35
